### ISSUE TITLE
Keywords

### ISSUE THREAD

**Issue by KristjanESPERANTO** [BrianHepler/MMM-BirdNET#6]
In [the new module list](https://modules.magicmirror.builders/) I am working on, tags are displayed for each module. These are read from the package.json. So far there are no keywords in the package.json of your module. It would be nice if you could add some. [Here you can see an example of a package.json with keywords.](https://github.com/jalibu/MMM-NINA/blob/04896f1ed9139059ea1b9d24ada4161d70e13030/package.json#L10)

This would be my suggestion:

```json
  "keywords": [
    "MagicMirror",
    "BirdNET",
    "bird",
    "birds",
    "Cornell University"
  ],
```

**Comment by BrianHepler** [comment]
Good suggestion. I have created the branch `keywords_notifications` with the keywords added. It also broadcasts a couple notifications and accepts one notification. Please give it a try and let me know if this is what you were looking for.

**Comment by KristjanESPERANTO** [comment]
Looks good :+1:

**Comment by KristjanESPERANTO** [comment]
Nice. Your module now looks perfect on the new list :rocket: Thanks! :smiley:
